package reverse;
// Generated Nov 20, 2022, 2:18:18 PM by Hibernate Tools 6.1.3.Final

/**
 * Listaempleados generated by hbm2java
 */
public class Listaempleados implements java.io.Serializable {

	private ListaempleadosId id;

	public Listaempleados() {
	}

	public Listaempleados(ListaempleadosId id) {
		this.id = id;
	}

	public ListaempleadosId getId() {
		return this.id;
	}

	public void setId(ListaempleadosId id) {
		this.id = id;
	}

}
